/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyPanels;

/**
 *
 * @author Claudio
 */
public class AggiornamentoPrezzo extends javax.swing.JPanel {

    /**
     * Creates new form AggiornamentoPrezzo
     */
    public AggiornamentoPrezzo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitolo = new javax.swing.JLabel();
        lbNomeProdotto = new javax.swing.JLabel();
        lbNuovoPrezzo = new javax.swing.JLabel();
        tfNomeProdotto = new javax.swing.JTextField();
        tfNuovoPrezzo = new javax.swing.JTextField();
        btnAggiorna = new javax.swing.JButton();
        btnAnnulla = new javax.swing.JButton();

        lbTitolo.setText("AGGIORNAMENTO PREZZO PRODOTTO");

        lbNomeProdotto.setText("Nome prodotto:");

        lbNuovoPrezzo.setText("Nuovo prezzo:");

        tfNomeProdotto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeProdottoActionPerformed(evt);
            }
        });

        tfNuovoPrezzo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNuovoPrezzoActionPerformed(evt);
            }
        });

        btnAggiorna.setText("Aggiorna");

        btnAnnulla.setText("Annulla");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(lbTitolo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbNomeProdotto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfNomeProdotto, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbNuovoPrezzo)
                                .addGap(18, 18, 18)
                                .addComponent(tfNuovoPrezzo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(btnAggiorna)
                        .addGap(77, 77, 77)
                        .addComponent(btnAnnulla)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lbTitolo)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNomeProdotto)
                    .addComponent(tfNomeProdotto, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNuovoPrezzo)
                    .addComponent(tfNuovoPrezzo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAggiorna)
                    .addComponent(btnAnnulla))
                .addGap(53, 53, 53))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tfNomeProdottoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeProdottoActionPerformed
        // TODO add your handling code here:
        String nomeProdotto=tfNomeProdotto.getText();
    }//GEN-LAST:event_tfNomeProdottoActionPerformed

    private void tfNuovoPrezzoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNuovoPrezzoActionPerformed
        // TODO add your handling code here:
        double nuovoPrezzo=Double.parseDouble(tfNuovoPrezzo.getText());
        System.out.println(nuovoPrezzo);
    }//GEN-LAST:event_tfNuovoPrezzoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAggiorna;
    private javax.swing.JButton btnAnnulla;
    private javax.swing.JLabel lbNomeProdotto;
    private javax.swing.JLabel lbNuovoPrezzo;
    private javax.swing.JLabel lbTitolo;
    private javax.swing.JTextField tfNomeProdotto;
    private javax.swing.JTextField tfNuovoPrezzo;
    // End of variables declaration//GEN-END:variables
}
