/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyPanels;

/**
 *
 * @author Claudio
 */
public class AggiungiProdotti extends javax.swing.JPanel {

    /**
     * Creates new form AggiungiProdottiGUI
     */
    public AggiungiProdotti() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfNomeProdotto = new javax.swing.JTextField();
        lbNomeProdotto = new javax.swing.JLabel();
        lbQuantità = new javax.swing.JLabel();
        bAggiungi = new javax.swing.JButton();
        bAnnulla = new javax.swing.JButton();
        lbTitolo = new javax.swing.JLabel();
        tfQuantitàP = new javax.swing.JTextField();
        lbMessaggio = new javax.swing.JLabel();
        lbQuantitàP = new javax.swing.JLabel();
        lbNomeP = new javax.swing.JLabel();

        tfNomeProdotto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeProdottoActionPerformed(evt);
            }
        });

        lbNomeProdotto.setText("Nome prodotto:");

        lbQuantità.setText("Quantità:");
        lbQuantità.setToolTipText("");

        bAggiungi.setText("Aggiungi");
        bAggiungi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAggiungiActionPerformed(evt);
            }
        });

        bAnnulla.setText("Annulla");

        lbTitolo.setText("AGGIUNGI PRODOTTO");

        tfQuantitàP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfQuantitàPActionPerformed(evt);
            }
        });

        lbMessaggio.setText("Stai aggiungendo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbTitolo)
                .addGap(142, 142, 142))
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(bAggiungi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bAnnulla)
                .addGap(61, 61, 61))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(lbQuantità)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfQuantitàP, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lbNomeProdotto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfNomeProdotto, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(lbMessaggio)
                        .addGap(36, 36, 36)
                        .addComponent(lbQuantitàP)
                        .addGap(46, 46, 46)
                        .addComponent(lbNomeP)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lbTitolo)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNomeProdotto)
                    .addComponent(tfNomeProdotto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbQuantità)
                    .addComponent(tfQuantitàP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMessaggio)
                    .addComponent(lbQuantitàP)
                    .addComponent(lbNomeP))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAggiungi)
                    .addComponent(bAnnulla))
                .addGap(48, 48, 48))
        );

        tfNomeProdotto.getAccessibleContext().setAccessibleName("");
        bAggiungi.getAccessibleContext().setAccessibleName("bAggiungi");
        bAnnulla.getAccessibleContext().setAccessibleName("bAnnulla");
    }// </editor-fold>//GEN-END:initComponents

    private void tfNomeProdottoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeProdottoActionPerformed
        // TODO add your handling code here:
        String nomeProdotto=tfNomeProdotto.getText();
        lbNomeP.setText("di "+nomeProdotto);
    }//GEN-LAST:event_tfNomeProdottoActionPerformed

    private void bAggiungiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAggiungiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bAggiungiActionPerformed

    private void tfQuantitàPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfQuantitàPActionPerformed
        // TODO add your handling code here:
        int quantitàProdotto=Integer.parseInt(tfQuantitàP.getText());
        lbQuantitàP.setText(quantitàProdotto+" pezzi");
    }//GEN-LAST:event_tfQuantitàPActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAggiungi;
    private javax.swing.JButton bAnnulla;
    private javax.swing.JLabel lbMessaggio;
    private javax.swing.JLabel lbNomeP;
    private javax.swing.JLabel lbNomeProdotto;
    private javax.swing.JLabel lbQuantità;
    private javax.swing.JLabel lbQuantitàP;
    private javax.swing.JLabel lbTitolo;
    private javax.swing.JTextField tfNomeProdotto;
    private javax.swing.JTextField tfQuantitàP;
    // End of variables declaration//GEN-END:variables
}
