/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyPanels;

/**
 *
 * @author Claudio
 */
public class CaricamentoMonete extends javax.swing.JPanel {

    private double saldo;
    /**
     * Creates new form CaricamentoMoneteGUI
     */
    public CaricamentoMonete() {
        initComponents();
        saldo=0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb10cent = new javax.swing.JLabel();
        lb5cent = new javax.swing.JLabel();
        lb20cent = new javax.swing.JLabel();
        lb50cent = new javax.swing.JLabel();
        lb1E = new javax.swing.JLabel();
        lb2E = new javax.swing.JLabel();
        lbTitolo = new javax.swing.JLabel();
        btnAggiorna = new javax.swing.JButton();
        btnAnnulla = new javax.swing.JButton();
        lbMessaggio = new javax.swing.JLabel();
        lbQuantità = new javax.swing.JLabel();
        tf5cent = new javax.swing.JTextField();
        tf10cent = new javax.swing.JTextField();
        tf20cent = new javax.swing.JTextField();
        tf50cent = new javax.swing.JTextField();
        tf1E = new javax.swing.JTextField();
        tf2E = new javax.swing.JTextField();

        lb10cent.setText("10 cent.");

        lb5cent.setText("5 cent.");

        lb20cent.setText("20 cent.");

        lb50cent.setText("50 cent.");

        lb1E.setText("1");

        lb2E.setText("2");

        lbTitolo.setText("CARICAMENTO MONETE");

        btnAggiorna.setText("Aggiorna");

        btnAnnulla.setText("Annulla");

        lbMessaggio.setText("Stai aggiungendo...");

        tf5cent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf5centActionPerformed(evt);
            }
        });

        tf10cent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf10centActionPerformed(evt);
            }
        });

        tf20cent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf20centActionPerformed(evt);
            }
        });

        tf50cent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf50centActionPerformed(evt);
            }
        });

        tf1E.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf1EActionPerformed(evt);
            }
        });

        tf2E.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf2EActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(btnAggiorna)
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbMessaggio)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAnnulla)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lbQuantità)))
                .addContainerGap(95, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lb20cent)
                            .addComponent(lb10cent)
                            .addComponent(lb5cent))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lb50cent)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lbTitolo)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf5cent, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(tf20cent, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lb2E))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(tf10cent, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lb1E, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(35, 35, 35)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tf50cent, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf1E, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf2E, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lbTitolo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb5cent, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb50cent)
                    .addComponent(tf5cent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf50cent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb10cent)
                    .addComponent(lb1E)
                    .addComponent(tf10cent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf1E, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb20cent)
                    .addComponent(lb2E)
                    .addComponent(tf20cent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf2E, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMessaggio)
                    .addComponent(lbQuantità))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAggiorna)
                    .addComponent(btnAnnulla))
                .addGap(27, 27, 27))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tf5centActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf5centActionPerformed
        // TODO add your handling code here:
        int quantità5cent=Integer.parseInt(tf5cent.getText());  
        saldo+=quantità5cent*0.05;
        lbQuantità.setText(saldo+"Euro");
    }//GEN-LAST:event_tf5centActionPerformed

    private void tf10centActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf10centActionPerformed
        // TODO add your handling code here:
        int quantità10cent=Integer.parseInt(tf10cent.getText());  
        saldo+=quantità10cent*0.10;
        lbQuantità.setText(saldo+"Euro");
    }//GEN-LAST:event_tf10centActionPerformed

    private void tf20centActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf20centActionPerformed
        // TODO add your handling code here:
        int quantità20cent=Integer.parseInt(tf20cent.getText());  
        saldo+=quantità20cent*0.20;
        lbQuantità.setText(saldo+"Euro");
    }//GEN-LAST:event_tf20centActionPerformed

    private void tf50centActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf50centActionPerformed
        // TODO add your handling code here:
        int quantità50cent=Integer.parseInt(tf50cent.getText());  
        saldo+=quantità50cent*0.50;
        lbQuantità.setText(saldo+"Euro");
    }//GEN-LAST:event_tf50centActionPerformed

    private void tf1EActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf1EActionPerformed
        // TODO add your handling code here:
        int quantità1E=Integer.parseInt(tf1E.getText());  
        saldo+=quantità1E*1.00;
        lbQuantità.setText(saldo+"Euro");
    }//GEN-LAST:event_tf1EActionPerformed

    private void tf2EActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf2EActionPerformed
        // TODO add your handling code here:
        int quantità2E=Integer.parseInt(tf2E.getText());  
        saldo+=quantità2E*2.00;
        lbQuantità.setText(saldo+"Euro");
    }//GEN-LAST:event_tf2EActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAggiorna;
    private javax.swing.JButton btnAnnulla;
    private javax.swing.JLabel lb10cent;
    private javax.swing.JLabel lb1E;
    private javax.swing.JLabel lb20cent;
    private javax.swing.JLabel lb2E;
    private javax.swing.JLabel lb50cent;
    private javax.swing.JLabel lb5cent;
    private javax.swing.JLabel lbMessaggio;
    private javax.swing.JLabel lbQuantità;
    private javax.swing.JLabel lbTitolo;
    private javax.swing.JTextField tf10cent;
    private javax.swing.JTextField tf1E;
    private javax.swing.JTextField tf20cent;
    private javax.swing.JTextField tf2E;
    private javax.swing.JTextField tf50cent;
    private javax.swing.JTextField tf5cent;
    // End of variables declaration//GEN-END:variables
}
