/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyPanels;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Claudio
 */
public class Menu extends javax.swing.JPanel {

    /**
     * Creates new form MenuGUI
     */
    public Menu() {
        initComponents();
        addRowToProdotto();
        addRowToMonete();
        Thread t=new Thread(new Orologio());
        t.start();
    }

    private class Orologio implements Runnable{
        GregorianCalendar orario;
        
        public void run() {
            while(true){
                orario=new GregorianCalendar();
                int ore=orario.get(Calendar.HOUR_OF_DAY);
                int minuti=orario.get(Calendar.MINUTE);
                int secondi=orario.get(Calendar.SECOND);
                if(minuti<10 && secondi<10){
                    lbOrologio.setText(ore+":0"+minuti+":0"+secondi);  
                }else if(minuti<10){
                    lbOrologio.setText(ore+":0"+minuti+":"+secondi);   
                }else if(secondi<10){
                    lbOrologio.setText(ore+":"+minuti+":0"+secondi);
                }else{
                   lbOrologio.setText(ore+":"+minuti+":"+secondi); 
                }
            }
        }
        
    } 
    
    private class Prodotto{
        private String nomeProdotto;
        private int quantità;

        public Prodotto(String nomeProdotto, int quantità) {
            this.nomeProdotto = nomeProdotto;
            this.quantità = quantità;
        }
         
    }
    
    private class Moneta{
        private String taglioMoneta;
        private int quantità;

        public Moneta(String taglioMoneta, int quantità) {
            this.taglioMoneta = taglioMoneta;
            this.quantità = quantità;
        } 
        
    }
    
     private ArrayList elencoProdotti()
        {
            ArrayList<Prodotto> elencoProdotti=new ArrayList<>();
            Prodotto p1=new Prodotto("Banane",15);
            Prodotto p2=new Prodotto("Pesche",20);
            Prodotto p3=new Prodotto("Prugne",40);   
            elencoProdotti.add(p1);
            elencoProdotti.add(p2);
            elencoProdotti.add(p3);
            return elencoProdotti;
        }
     
     private void addRowToProdotto(){
         DefaultTableModel model= (DefaultTableModel) tbProdotti.getModel();
         ArrayList<Prodotto> elenco=elencoProdotti();
         Object rowData[]=new Object[2];
         for(int i=0;i<elenco.size();i++){
             rowData[0]=elenco.get(i).nomeProdotto;
             rowData[1]=elenco.get(i).quantità;
             model.addRow(rowData);
         }   
     }
     
     private ArrayList elencoMonete()
     {
         ArrayList<Moneta> elencoMonete=new ArrayList<>();
         Moneta m1=new Moneta("5 cent.",10);
         Moneta m2=new Moneta("10 cent.",20);
         Moneta m3=new Moneta("20 cent.",20);
         Moneta m4=new Moneta("50 cent.",10);
         Moneta m5=new Moneta("1 Euro",30);
         Moneta m6=new Moneta("2 Euro",20);
         elencoMonete.add(m1);
         elencoMonete.add(m2);
         elencoMonete.add(m2);
         elencoMonete.add(m3);
         elencoMonete.add(m4);
         elencoMonete.add(m5);
         elencoMonete.add(m6);
         return elencoMonete;  
     }
     
     private void addRowToMonete(){
         DefaultTableModel model=(DefaultTableModel) tbMoneteResto.getModel();
         ArrayList<Moneta> elenco=elencoMonete();
         Object rowData[]=new Object[2];
         for(int i=0;i<elenco.size();i++){
             rowData[0]=elenco.get(i).taglioMoneta;
             rowData[1]=elenco.get(i).quantità;
             model.addRow(rowData);
         }
     }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        incasso = new javax.swing.JLabel();
        lbIncasso = new javax.swing.JLabel();
        btnRitiraIncasso = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbProdotti = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbMoneteResto = new javax.swing.JTable();
        lbTitoloTProdotti = new javax.swing.JLabel();
        lbTitoloTMonete = new javax.swing.JLabel();
        lbOrologio = new javax.swing.JLabel();

        incasso.setText("INCASSO:");

        lbIncasso.setText("jLabel3");

        btnRitiraIncasso.setText("Ritira incasso");

        tbProdotti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome prodotto", "Quantità"
            }
        ));
        jScrollPane2.setViewportView(tbProdotti);

        tbMoneteResto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Taglio moneta", "Quantità"
            }
        ));
        jScrollPane1.setViewportView(tbMoneteResto);

        lbTitoloTProdotti.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        lbTitoloTProdotti.setText("Tabella prodotti:");

        lbTitoloTMonete.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        lbTitoloTMonete.setText("Tabella monete resto:");

        lbOrologio.setFont(new java.awt.Font("New Peninim MT", 1, 48)); // NOI18N
        lbOrologio.setForeground(new java.awt.Color(255, 255, 255));
        lbOrologio.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(incasso)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbIncasso))
                            .addComponent(btnRitiraIncasso))
                        .addContainerGap(166, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lbOrologio, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(lbTitoloTMonete))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(lbTitoloTProdotti)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lbTitoloTProdotti)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbOrologio, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(incasso)
                            .addComponent(lbIncasso)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)))
                .addGap(17, 17, 17)
                .addComponent(lbTitoloTMonete)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(btnRitiraIncasso)))
                .addGap(68, 68, 68))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRitiraIncasso;
    private javax.swing.JLabel incasso;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbIncasso;
    private javax.swing.JLabel lbOrologio;
    private javax.swing.JLabel lbTitoloTMonete;
    private javax.swing.JLabel lbTitoloTProdotti;
    private javax.swing.JTable tbMoneteResto;
    private javax.swing.JTable tbProdotti;
    // End of variables declaration//GEN-END:variables
}
