
import MyPanels.*;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Claudio
 */
public class mainFrame extends javax.swing.JFrame {
    
    GridBagLayout layout= new GridBagLayout();
    
    Menu p; 
    AggiornamentoPrezzo p1; 
    AggiungiProdotti p2; 
    CaricamentoMonete p3;
    LogOut p4;
    LogIn p5;
    AggiornamentoPrezzo p6;
    

    /**
     * Creates new form mainFrame
     */
    public mainFrame() {
        initComponents();
        p= new Menu();
        p1= new AggiornamentoPrezzo();
        p2= new AggiungiProdotti();
        p3= new CaricamentoMonete();
        p4= new LogOut();
        p5= new LogIn();
        
        DynamicPanel.setLayout(layout);
        GridBagConstraints c= new GridBagConstraints();
        c.anchor=GridBagConstraints.CENTER;
        
        DynamicPanel.add(p,c);
        DynamicPanel.add(p1,c);
        DynamicPanel.add(p2,c);
        DynamicPanel.add(p3,c);
        DynamicPanel.add(p4,c);
        DynamicPanel.add(p5,c);
        
        p.setVisible(true);
        p1.setVisible(false); 
        p2.setVisible(false); 
        p3.setVisible(false);
        p4.setVisible(false);
        p5.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DynamicPanel = new javax.swing.JPanel();
        jMenu = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mnuAggProdotti = new javax.swing.JMenuItem();
        mnuLoadMResto = new javax.swing.JMenuItem();
        mnuAggPrezzoP = new javax.swing.JMenuItem();
        mnuMenu = new javax.swing.JMenuItem();
        mnuExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(850, 900));

        DynamicPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout DynamicPanelLayout = new javax.swing.GroupLayout(DynamicPanel);
        DynamicPanel.setLayout(DynamicPanelLayout);
        DynamicPanelLayout.setHorizontalGroup(
            DynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 566, Short.MAX_VALUE)
        );
        DynamicPanelLayout.setVerticalGroup(
            DynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 409, Short.MAX_VALUE)
        );

        mnuFile.setText("File");

        mnuAggProdotti.setText("Aggiungi prodotti");
        mnuAggProdotti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAggProdottiActionPerformed(evt);
            }
        });
        mnuFile.add(mnuAggProdotti);

        mnuLoadMResto.setText("Carica monete resto");
        mnuLoadMResto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLoadMRestoActionPerformed(evt);
            }
        });
        mnuFile.add(mnuLoadMResto);

        mnuAggPrezzoP.setText("Aggiorna prezzo prodotti");
        mnuAggPrezzoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAggPrezzoPActionPerformed(evt);
            }
        });
        mnuFile.add(mnuAggPrezzoP);

        mnuMenu.setText("Torna al menu");
        mnuMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMenuActionPerformed(evt);
            }
        });
        mnuFile.add(mnuMenu);

        mnuExit.setText("Esci");
        mnuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuExitActionPerformed(evt);
            }
        });
        mnuFile.add(mnuExit);

        jMenu.add(mnuFile);

        setJMenuBar(jMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DynamicPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DynamicPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuExitActionPerformed
        // TODO add your handling code here:
        p.setVisible(false);
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(true);
        p5.setVisible(false);
    }//GEN-LAST:event_mnuExitActionPerformed

    private void mnuAggProdottiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAggProdottiActionPerformed
        // TODO add your handling code here:
        p.setVisible(false);
        p1.setVisible(false);
        p2.setVisible(true);
        p3.setVisible(false);
        p4.setVisible(false);
        p5.setVisible(false);
    }//GEN-LAST:event_mnuAggProdottiActionPerformed

    private void mnuAggPrezzoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAggPrezzoPActionPerformed
        // TODO add your handling code here:
        p.setVisible(false);
        p1.setVisible(true);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
        p5.setVisible(false);
    }//GEN-LAST:event_mnuAggPrezzoPActionPerformed

    private void mnuMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMenuActionPerformed
        // TODO add your handling code here:
        p.setVisible(true);
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
    }//GEN-LAST:event_mnuMenuActionPerformed

    private void mnuLoadMRestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLoadMRestoActionPerformed
        // TODO add your handling code here:
        p.setVisible(false);
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(true);
        p4.setVisible(false);
        p5.setVisible(false);
    }//GEN-LAST:event_mnuLoadMRestoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DynamicPanel;
    private javax.swing.JMenuBar jMenu;
    private javax.swing.JMenuItem mnuAggPrezzoP;
    private javax.swing.JMenuItem mnuAggProdotti;
    private javax.swing.JMenuItem mnuExit;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenuItem mnuLoadMResto;
    private javax.swing.JMenuItem mnuMenu;
    // End of variables declaration//GEN-END:variables
}
